# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rejection_computation_cpp <- function(mean_list, sd_list, side, cutoff) {
    .Call(`_perturbplan_rejection_computation_cpp`, mean_list, sd_list, side, cutoff)
}

FDP_estimate_cpp <- function(mean_list, sd_list, side, cutoff, QC_prob) {
    .Call(`_perturbplan_FDP_estimate_cpp`, mean_list, sd_list, side, cutoff, QC_prob)
}

fdp_hat_cpp <- function(t, mean_list, sd_list, side, QC_prob) {
    .Call(`_perturbplan_fdp_hat_cpp`, t, mean_list, sd_list, side, QC_prob)
}

BH_cutoff_cpp <- function(mean_list, sd_list, side, multiple_testing_alpha, QC_prob) {
    .Call(`_perturbplan_BH_cutoff_cpp`, mean_list, sd_list, side, multiple_testing_alpha, QC_prob)
}

BH_cutoff_bi <- function(mean_list, sd_list, side, multiple_testing_alpha, QC_prob) {
    .Call(`_perturbplan_BH_cutoff_bi`, mean_list, sd_list, side, multiple_testing_alpha, QC_prob)
}

compute_QC_fixed_es_cpp <- function(fold_change, expression_mean, expression_size, num_cntrl_cells, num_cells, n_nonzero_trt_thresh = 7L, n_nonzero_cntrl_thresh = 7L) {
    .Call(`_perturbplan_compute_QC_fixed_es_cpp`, fold_change, expression_mean, expression_size, num_cntrl_cells, num_cells, n_nonzero_trt_thresh, n_nonzero_cntrl_thresh)
}

compute_distribution_teststat_fixed_es_cpp <- function(fold_change, expression_mean, expression_size, num_trt_cells, num_cntrl_cells, num_cells) {
    .Call(`_perturbplan_compute_distribution_teststat_fixed_es_cpp`, fold_change, expression_mean, expression_size, num_trt_cells, num_cntrl_cells, num_cells)
}

compute_distribution_teststat_fixed_es_random_assignment_cpp <- function(fold_change, expression_mean, expression_size, num_cntrl_cells, mean_num_cells, sd_num_cells, B = 1000L) {
    .Call(`_perturbplan_compute_distribution_teststat_fixed_es_random_assignment_cpp`, fold_change, expression_mean, expression_size, num_cntrl_cells, mean_num_cells, sd_num_cells, B)
}

