# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rejection_computation_cpp <- function(mean_list, sd_list, side, cutoff) {
    .Call(`_perturbplan_rejection_computation_cpp`, mean_list, sd_list, side, cutoff)
}

FDP_estimate_cpp <- function(mean_list, sd_list, side, cutoff, QC_prob) {
    .Call(`_perturbplan_FDP_estimate_cpp`, mean_list, sd_list, side, cutoff, QC_prob)
}

fdp_hat_cpp <- function(t, mean_list, sd_list, side, QC_prob) {
    .Call(`_perturbplan_fdp_hat_cpp`, t, mean_list, sd_list, side, QC_prob)
}

BH_cutoff_cpp <- function(mean_list, sd_list, side, multiple_testing_alpha, QC_prob) {
    .Call(`_perturbplan_BH_cutoff_cpp`, mean_list, sd_list, side, multiple_testing_alpha, QC_prob)
}

BH_cutoff_bi <- function(mean_list, sd_list, side, multiple_testing_alpha, QC_prob) {
    .Call(`_perturbplan_BH_cutoff_bi`, mean_list, sd_list, side, multiple_testing_alpha, QC_prob)
}

